### ISSUE TITLE
Handle VERSION file with newline

### ISSUE THREAD

**Issue by mfikes** [james-henderson/simple-brepl#10]
Cope with the possibility that the VERSION file may have a newline at the end.

Rationale: If someone grabs this repo and updates the VERSION file (perhaps adding a -SNAPSHOT suffix to facilitate local development) and their editor inadvertently adds a newline (`vi` will do it), then this results in messing up the local Maven repo—it puts the newline in certain paths. This is challenging to sort out.

This could be coped with by wrapping the few places where it is `slurp`ed in with a `.trim`.

**Comment by mfikes** [comment]
Hey @james-henderson I can understand if you'd prefer not to address this issue, as it makes the code a little more complex.

An alternative to consider is to eliminate the use of the VERSION file. It's use in `project.clj` evidently confuses Cursive, which is probably expecting a string literal, FWIW.

In short, none of the above is really an issue with `simple-brepl` itself, but is in how it might be used.

**Comment by james-henderson** [comment]
Fixed by #11, thanks for the PR :)

**Comment by james-henderson** [comment]
I agree with trying to eliminate the use of the VERSION file, btw - that can't be the most idiomatic way to ensure that all the project.clj's have the same version number!

**Comment by mfikes** [comment]
No problem. Lein seems to support it, so things like Cursive ultimately should as well.
