### ISSUE TITLE
Catch up with latest ClojureScript

### ISSUE THREAD

**Issue by viesti** [james-henderson/simple-brepl#12]
Piggieback now supports ClojureScript >= 2665: https://github.com/cemerick/piggieback/blob/master/CHANGES.md#014. So for simple-brepl to work with newer ClojureScript, depedencies should be updated (maybe check that stuff still works too :)).

**Comment by mfikes** [comment]
Weasel is also [being updated](https://github.com/tomjakubowski/weasel/issues/37).

**Comment by viesti** [comment]
Ah true. Was jumping ahead of things :)

**Comment by james-henderson** [comment]
Thanks both - I'll keep an eye on the progress in Weasel and update simple-brepl as and when it's stable.

Cheers :)

James

**Comment by mfikes** [comment]
Looks like Weasel and Piggieback now have releases supporting latest ClogureScript (0.0-2665).

**Comment by james-henderson** [comment]
Thanks @mfikes - will cut a new version in the morning.

James

**Comment by james-henderson** [comment]
Thanks Mike - have cut simple-brepl 0.2.0 - looks good from here but let me know if it works for you?

**Comment by mfikes** [comment]
I _think_ we may need piggieback 0.1.5.

A test I tried was to switch namespaces and do things in that namespace, and that bit is not working.

**Comment by mfikes** [comment]
Specifically, without piggyback 0.1.5, I get an `ArityException` when switching namespaces.

```
(in-ns 'shrimp.detail-view-controller)
ArityException Wrong number of args (2) passed to: repl/fn--4253/self--4259  clojure.lang.AFn.throwArity (AFn.java:429)
```

The problem is that simply updating simple-brepl alone doesn't appear to solve this. If I put piggyback 0.1.5 as a project dependency, things work. I'm wondering if Weasel specifying piggyback 0.1.4 is causing an issue. (I would have expected simple-brepl to be able to override that dependency.)

**Comment by mfikes** [comment]
@james-henderson I did some further cleaning and rebuilding and came to the conclusion that updating the dependency in simple-brepl to piggieback 0.1.5 is sufficient, as expected. This resolves the `ArityException` problem that you get when using the `(in-ns ...)` REPL special form.

**Comment by jarohen** [comment]
Thanks Mike - I've updated Piggieback to 0.1.5 and released simple-brepl 0.2.1

**Comment by mfikes** [comment]
@james-henderson I've confirmed that simple-brepl 0.2.1 works and supports switching namespaces. I confirmed it with [a commit](https://github.com/mfikes/shrimp/commit/35bcc831fb62d98c2ae10bd55f77086bd251cc71) in [this project](https://github.com/mfikes/shrimp).

**Comment by jarohen** [comment]
Looks good to me - thanks for your help!
