### ISSUE TITLE
java.lang.IllegalStateException when using the Ultra library

### ISSUE THREAD

**Issue by cwhitey** [james-henderson/simple-brepl#14]
I was unsure which GitHub project to submit this issue to (here or [Ultra](https://github.com/venantius/ultra)), so I'm just starting here.
I've been experimenting with the simple-brepl sample in this repo and was getting the following error when executing `(simple-brepl)` in the nREPL:

```
java.lang.IllegalStateException: Can't change/establish root binding of: *cljs-repl-options* with set
```

I'm connecting to the nREPL using `lein repl :connect 7888`. After some debugging I found that removing [Ultra](https://github.com/venantius/ultra) from my `~/.lein/profiles.clj` dependencies list fixed the issue, and running `(simple-brepl)` would successfully create a ClojureScript REPL. I'd like to use both Ultra and simple-brepl, so any insight as to what's causing this issue would be appreciated.

**Comment by jarohen** [comment]
Hi Callum - thanks for letting me know. Will take a look!

James

**Comment by jarohen** [comment]
Hi Callum - do you get a stack trace with that error?

**Comment by jarohen** [comment]
(cc'ing @venantius in case he has any ideas from Ultra's side!)

**Comment by cwhitey** [comment]
Sorry, completely forgot about the stack trace. This is all I get:

![stack_trace1](https://cloud.githubusercontent.com/assets/8540661/6020716/633f1cba-ac03-11e4-9a88-102a9a04cbbd.jpg)

**Comment by jarohen** [comment]
No worries! Sorry - could you also attach a `lein deps :tree`?

Thanks

**Comment by cwhitey** [comment]
Sure thing! This is within a fresh splat template project (as was the previous stack trace posted):
[PASTEBIN](http://pastebin.com/LcsFyRyN)

**Comment by venantius** [comment]
Hey @cwhitey - would you mind selectively disabling Ultra's features (https://github.com/venantius/ultra#configuration) so we can confirm which one is the root of the problem? I strongly suspect it's going to be `:repl`, and probably [fipp](https://github.com/brandonbloom/fipp) at the bottom of it, but we might as well go through the routine debugging steps.

**Comment by venantius** [comment]
After some poking around, I think the TL;DR is that the pretty-printer Ultra relies on - Fipp - doesn't currently have Cljs/Cljx support and is waiting on feature expressions in Clojure 1.7 to add support (see https://github.com/brandonbloom/fipp/issues/7). I'd advise that in the near term you just disable Ultra's `:repl`.

**Comment by cwhitey** [comment]
Cool, that works. I guess I'll just be hanging out for that fipp update now.

Thanks guys!

**Comment by jarohen** [comment]
Glad you got it sorted!
