### ISSUE TITLE
run (simple-brepl)

### ISSUE THREAD

**Issue by calvinirwan** [james-henderson/simple-brepl#8]
Hi, I'm a newbie, I just don't understand how to run "(simple-brepl)" in clojure repl.
What should i require first ?

**Comment by mfikes** [comment]
@calvinirwan If you include `[jarohen/simple-brepl "0.1.2"]` in your `:plugins` directive in your `project.clj`, you should be able to run `(simple-brepl)` in your REPL. Are you getting an error?

**Comment by calvinirwan** [comment]
i tried it again and it works, thanks @mfikes

**Comment by james-henderson** [comment]
Thanks for your quick response, Mike!
